#cp $GITHUB_WORKSPACE/lede/legacy.mk $GITHUB_WORKSPACE/openwrt/target/linux/ar71xx/image/legacy.mk
#cp $GITHUB_WORKSPACE/lede/common-tp-link.mk $GITHUB_WORKSPACE/openwrt/target/linux/ar71xx/image/common-tp-link.mk
cp $GITHUB_WORKSPACE/lede/shadow $GITHUB_WORKSPACE/openwrt/package/base-files/files/etc/shadow
cp $GITHUB_WORKSPACE/lede/hosts $GITHUB_WORKSPACE/openwrt/package/base-files/files/etc/hosts
cp $GITHUB_WORKSPACE/lede/config_generate $GITHUB_WORKSPACE/openwrt/package/base-files/files/bin/config_generate
cp $GITHUB_WORKSPACE/lede/mac80211.sh $GITHUB_WORKSPACE/openwrt/package/kernel/mac80211/files/lib/wifi/mac80211.sh
#cp $GITHUB_WORKSPACE/lede/luci $GITHUB_WORKSPACE/openwrt/feeds/luci/modules/luci-base/root/etc/config/luci
cp $GITHUB_WORKSPACE/lede/dhcp.conf $GITHUB_WORKSPACE/openwrt/package/network/services/dnsmasq/files/dhcp.conf
#cp $GITHUB_WORKSPACE/lede/dnsmasq.conf $GITHUB_WORKSPACE/openwrt/package/network/services/dnsmasq/files/dnsmasq.conf
